server {
    listen 80;
    
    # Abilita la compressione GZIP per rendere il sito più veloce
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # Questa è la vera magia per le SPA:
        # "Se non trovi il file o la cartella, servi index.html"
        try_files $uri $uri/ /index.html;
    }

    # (Opzionale) Gestione degli errori lato server
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}